#!/usr/bin/env bash
set -euo pipefail

sudo pacman -S --needed archlinux-xdg-menu kservice
sudo mkdir -p /etc/pacman.d/hooks/
sudo cp "$DOTDIR/hyprland/meta/updateKDEcache.hook" /etc/pacman.d/hooks/updateKDEcache.hook
