[config]
version_check = false
caching = false
expr_prefix = "{{"
expr_postfix = "}}"
block_prefix = "<*"
block_postfix = "*>"

[config.wallpaper]
command = "set_wallpaper {{ image }}"
set = true

[templates.pywalfox]
input_path = 'templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update; pywalfox {{mode | lower_case}}'

[templates.gtk3]
input_path = 'templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme {{ mode | replace: "light", "adw-gtk3" | replace: "dark", "adw-gtk3-dark" }}; gsettings set org.gnome.desktop.interface color-scheme {{ mode | replace: "light", "default" | replace: "dark", "prefer-dark" }}'

[templates.gtk4]
input_path = 'templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt]
input_path = 'templates/qt.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.zellij]
input_path = 'templates/zellij.kdl'
output_path = '~/.config/zellij/themes/matugen.kdl'
post_hook = 'touch ~/.config/zellij/config.kdl'

[templates.quickshell]
input_path = "templates/quickshell.json"
output_path = "~/.config/quickshell/config/palette.json"

[templates.hyprland]
input_path = "templates/hyprland.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = 'hyprctl setcursor "{{ mode | replace: "light", "Bibata-Modern-Ice" | replace: "dark", "Bibata-Modern-Classic" }}" 24'

[templates.ghostty]
input_path = "templates/ghostty"
output_path = "~/.config/ghostty/colors"
post_hook = "kill -s USR2 $(pgrep ghostty)"

[templates.foot]
input_path = "templates/foot.ini"
output_path = "~/.config/foot/colors.ini"
post_hook = "python3 ~/.config/matugen/push_term_colors.py ~/.config/foot/colors.ini"

[templates.materialized-web]
input_path = "templates/materialized-web.json"
output_path = "~/.config/matugen/materialized-web/scheme/current.json"

[templates.nvim]
input_path = "templates/nvim.lua"
output_path = "~/.local/share/nvim/matugen.lua"

[templates.tshell]
input_path = "templates/tshell.toml"
output_path = "~/.config/tshell/colors.toml"
