#!/usr/bin/env bash

# Must be run from $HOME or it will not work

if [ $# -lt 2 ]; then
    echo "Usage: df-track [package] [...path]"
    echo "Must be run from $HOME or it will not work"
    exit 1
fi

package="$1"
shift

for path in "$@"; do
    # Normalize leading ~
    rel="${path/#\~\//}"

    mkdir -p "$HOME/dotfiles/$package/$(dirname "$rel")"

    mv "$HOME/$rel" "$HOME/dotfiles/$package/$rel"
done

# Run stow from parent directory
( cd "$HOME/dotfiles" && stow "$package" )

